version: '3'

volumes:
      produtosdata:

networks:
      frontend:
      backend:

services:

      mysql:
        image: "mysql:5.7"
        volumes:
          - produtosdata:/var/lib/mysql
        networks:
          - backend
        environment:
          - MYSQL_ROOT_PASSWORD=root
          - bind-address=0.0.0.0